### ISSUE TITLE
Not able to make the module work

### ISSUE THREAD

**Issue by tushardave26** [felixfbecker/semantic-release-docker#31]
Hello @felixfbecker,

Thanks for making this module.

Recently, I started playing with it. Unfortunately, I am not able to make it work though.

Below are the things that I have tried so far.

# System information

```bash
# System information
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

# NPM version
$ npm --version
6.10.3

# Nodejs version
$ nodejs --version
v10.16.2

# semantic-release-docker information
$ npm list -g semantic-release-docker
/usr/lib
└── semantic-release-docker@2.2.0 
```

# .releaserc file content
```bash
{                                                                                                                                                     
    "branch": "master",                                                                                                                               
    "repositoryUrl": "https://github.com/labdave/RNAUtils.git",                                                                                       
    "tagFormat": "version-${version}",                                                                                                                
    "dryRun": "true",                                                                                                                                 
    "ci": "false",                                                                                                                                    
    "verifyConditions": {                                                                                                                             
        "path": "semantic-release-docker",                                                                                                            
        "registryUrl": "docker.io"                                                                                                                    
    },                                                                                                                                                
    "plugins": [                                                                                                                                      
        "@semantic-release/commit-analyzer",                                                                                                          
        "@semantic-release/release-notes-generator",                                                                                                  
        "@semantic-release/git",                                                                                                                      
        "@semantic-release/github",                                                                                                                   
        "semantic-release-docker",                                                                                                                    
        [                                                                                                                                             
            "@semantic-release/changelog",                                                                                                            
            {                                                                                                                                         
                "changelogFile": "CHANGELOG.md",                                                                                                      
                "changelogTitle": "# Semantic Versioning Changelog"                                                                                   
            }                                                                                                                                         
        ],                                                                                                                                            
        [                                                                                                                                             
            "@semantic-release/exec",                                                                                                                 
            {                                                                                                                                         
                "prepareCmd": "./prepare-release.sh ${nextRelease.version}"                                                                           
            }                                                                                                                                         
        ],                                                                                                                                            
    ],                                                                                                                                                
    "publish": [                                                                                                                                      
        {                                                                                                                                             
            "path": "semantic-release-docker",                                                                                                        
            "name": "davelabhub/RNAUtils:${nextRelease.version}"
         }                                                                                                                                             
    ],                                                                                                                                                
}
```

# error while executing sematic-release command
```bash
$ npx semantic-release 
[12:49:08 PM] [semantic-release] › ℹ  Running semantic-release version 15.13.19
[12:49:09 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[12:49:09 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[12:49:09 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "semantic-release-docker"
[12:49:09 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[12:49:09 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/exec"
[12:49:09 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[12:49:09 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/exec"
[12:49:09 PM] [semantic-release] › ✔  Loaded plugin "verifyRelease" from "@semantic-release/exec"
[12:49:09 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[12:49:09 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/exec"
[12:49:09 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[12:49:09 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[12:49:09 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/exec"
[12:49:09 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[12:49:09 PM] [semantic-release] › ✔  Loaded plugin "publish" from "semantic-release-docker"
[12:49:09 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/exec"
[12:49:09 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[12:49:09 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/exec"
[12:49:09 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[12:49:09 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/exec"
[12:49:09 PM] [semantic-release] › ⚠  Run automated release from branch master in dry-run mode
[12:49:09 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[12:49:09 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[12:49:09 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[12:49:09 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[12:49:09 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[12:49:09 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[12:49:09 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "semantic-release-docker"
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/auth: dial unix /var/run/docker.sock: connect: permission denied
[12:49:09 PM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "semantic-release-docker"
[12:49:09 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[12:49:09 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[12:49:09 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/exec"
[12:49:09 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/exec"
[12:49:09 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: docker login failed
    at module.exports (/usr/lib/node_modules/semantic-release-docker/lib/verify.js:23:11)
    at process._tickCallback (internal/process/next_tick.js:68:7) pluginName: 'semantic-release-docker' }
{ AggregateError: 
    Error: docker login failed
        at module.exports (/usr/lib/node_modules/semantic-release-docker/lib/verify.js:23:11)
    at /usr/lib/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'AggregateError' }
```
***NOTE:*** I provided `DOCKER_USERNAME` and `DOCKER_PASSWORD` as enviornment variable.

```bash
export DOCKER_USERNAME=davelabhub
export DOCKER_PASSWORD=***
```

Can you please help me to figure out the issue?

Thanks,
Tushar

**Comment by kybarg** [comment]
@tushardave26 have you solved this? same issue...

**Comment by tushardave26** [comment]
@kybarg - nope. I have not received any response from @felixfbecker. I tried multiple things, but none of them worked. So, I gave up.

**Comment by kybarg** [comment]
@tushardave26 If you are using Circle CI this should work
```yaml
release:
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Publish release
          command: |
            npm run semantic-release || true
```

`setup_remote_docker` is what allows to run docker commands within container

**Comment by tushardave26** [comment]
Thanks, @kybarg. I will try that whenever I get a chance.

**Comment by iot-resister** [comment]
Any tips on getting this to work with gitlab ci? getting an error at `verify.js:23:11`

I added the following to the gitlab config.

```yaml
  services:
    - docker:20.10.16-dind
 ```
 
 ref: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker
 
 I didn't have to do this on previous projects....
